### ISSUE TITLE
Chance moves probabilities parse errors not handled

### ISSUE THREAD

**Issue by vegaro** [gambitproject/jsgte#42]
When setting a probability of something different to a fraction, the contentEditable fails and sets to NaN.

Setting a probability of 12:

<img width="411" alt="captura de pantalla 2015-10-09 a las 17 02 26" src="https://cloud.githubusercontent.com/assets/664544/10397351/90d2ff86-6ea7-11e5-95c6-6a33d9744dac.png">

**Comment by amanvar** [comment]
@vegaro I am newbie in this org. Can you elaborate about this bug.

**Comment by vegaro** [comment]
Hi @amanvar. Welcome to the org! This issue is fixed. I am going to close it

**Comment by amanvar** [comment]
ok, @vegaro can you give some issues which easy to fix as I am new in this org.
