### ISSUE TITLE
Merging a node with its parent has weird behavior

### ISSUE THREAD

**Issue by alfongj** [gambitproject/jsgte#45]
(May be related to #44 )
Steps to reproduce:
1. Create this tree:
![image](https://cloud.githubusercontent.com/assets/822670/10569456/14c1b0dc-75db-11e5-9ed6-c4f692fc461b.png)
2. Try to merge the bottom-most node with its parent and get this:
![image](https://cloud.githubusercontent.com/assets/822670/10569440/e57507de-75da-11e5-8c2d-94875ded2891.png)

**Comment by alfongj** [comment]
I just checked, and in the same tree, trying to merge the father with the children (i.e., same operation, but operators in inverse order), the same happens.

**Comment by vegaro** [comment]
@alfongj @stengel As far as I understand, Nodes that do share a path from the root cannot be merged. This means that a node cannot be merged with other node contained on its path to root. Am I right?

I have fixed this issue and #46 by not letting users merging two nodes when one of them is on the other one's path to root. I am not sure this fix is correct. Can you illustrate me?
